config/routes.rb
require 'sidekiq/web'
require 'flipper/ui'

Cortex::Engine.routes.draw do
  # API - TODO: Authorize GraphQL + GraphiQL
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: ENV['GRAPHQL_URL'], as: 'graphiql'
  scope '/graphql' do
    post '/', to: 'graphql#execute'
    get '/ide', to: 'graphql#ide', as: 'graphql_ide'
  end

  root 'dashboards#index'

  scope '/admin_update' do
    match '/tenant_change', to: 'tenants#switch_tenants', via: [:post]
  end

  scope '/admin' do
    resources :dashboards
    resources :medias
  end

  resources :content_types do
    resources :content_items
  end

  # Authentication
  devise_for :users, controllers: {sessions: 'cortex/authentication/sessions', passwords: 'cortex/authentication/passwords'}, class_name: 'Cortex::User', module: :devise

  # Sidekiq Admin TODO: this needs to be updated with new role system
  #authenticate :user, lambda { |u| u.is_admin? } do
  mount Sidekiq::Web => '/sidekiq'
  #end

  # Flipper TODO: this needs to be updated with new role system
  #authenticated :user, lambda {|u| u.is_admin? } do
  mount Flipper::UI.app(Flipper) => '/flipper'
  #end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
end

app/models/concerns/cortex/belongs_to_tenant.rb
module Cortex
  module BelongsToTenant
    extend ActiveSupport::Concern

    included do
      belongs_to :tenant

      validates :tenant, presence: true

      scope :find_by_tenant, ->(tenant) { where(tenant_id: tenant.id) }
    end
  end
end

app/models/concerns/cortex/has_firstname_lastname.rb
module Cortex
  module HasFirstnameLastname
    extend ActiveSupport::Concern

    included do
      def fullname
        lastname.to_s == '' ? firstname : "#{firstname} #{lastname}"
      end
    end
  end
end

app/models/concerns/cortex/has_gravatar.rb
module Cortex
  module HasGravatar
    extend ActiveSupport::Concern

    included do
      def avatars
        hash = email ? Digest::MD5.hexdigest(email) : '00000000000000000000000000000000'
        url = "//www.gravatar.com/avatar/#{hash}"
        {
          default: "#{url}",
          small: "#{url}?s=200",
          medium: "#{url}?s=400",
          large: "#{url}?s=1000"
        }
      end
    end
  end
end

app/models/concerns/cortex/searchable.rb
module Cortex
  module Searchable
    extend ActiveSupport::Concern

    included do
      include Elasticsearch::Model

      index_name "#{Rails.env}_#{model_name.to_s.parameterize(separator: '_')}"
    end
  end
end

app/models/concerns/cortex/searchable_content_item.rb
module Cortex
  module SearchableContentItem
    extend ActiveSupport::Concern

    included do
      include Cortex::Searchable

      after_commit on: [:create] do
        __elasticsearch__.index_document(index: content_type.content_items_index_name)
      end

      after_commit on: [:update] do
        # Perform a full document re-index, as update_document ignores methods: https://github.com/elastic/elasticsearch-rails/issues/306#issuecomment-121817954
        __elasticsearch__.index_document(index: content_type.content_items_index_name)
      end

      after_commit on: [:destroy] do
        __elasticsearch__.delete_document(index: content_type.content_items_index_name)
      end

      def as_indexed_json(options = {})
        json = as_json
        field_items.each do |field_item|
          field_type = field_item.field.field_type_instance(field_name: field_item.field.name)
          json.merge!(field_type.field_item_as_indexed_json_for_field_type(field_item))
        end
        json
      end
    end
  end
end

app/models/concerns/cortex/searchable_content_item_for_content_type.rb
module Cortex
  module SearchableContentItemForContentType
    extend ActiveSupport::Concern

    included do
      after_commit on: [:create] do
        self.class.__elasticsearch__.create_index!(index: content_items_index_name, mappings: content_item_mappings)
      end

      after_commit on: [:destroy] do
        self.class.__elasticsearch__.delete_index!(index: content_items_index_name)
      end

      after_commit on: [:update] do
        self.class.__elasticsearch__.delete_index!(index: content_items_index_name)
        self.class.__elasticsearch__.create_index!(index: content_items_index_name, mappings: content_item_mappings)
        # TODO: implement & move import to ContentItem to mass-refresh all ContentItems for a ContentType
        #self.class.__elasticsearch__.import()
      end

      def content_items_index_name
        @content_items_index_name ||= "#{Rails.env}_content_type_#{name_id}_content_items"
      end
    end

    private

    def content_item_mappings
      mappings = Elasticsearch::Model::Indexing::Mappings.new(content_items_index_name, { dynamic: false })
      mappings.indexes :tenant_id, type: :keyword, index: :not_analyzed
      mappings.indexes :content_type_id, type: :keyword, index: :not_analyzed
      mappings.indexes :creator_id, type: :keyword, index: :not_analyzed
      mappings.indexes :updated_by_id, type: :keyword, index: :not_analyzed
      mappings.indexes :state, analyzer: :keyword, index: :not_analyzed
      mappings.indexes :created_at, type: :date, include_in_all: false
      mappings.indexes :updated_at, type: :date, include_in_all: false
      mappings.indexes :deleted_at, type: :date, include_in_all: false

      fields.each do |field|
        mappings.indexes field.elasticsearch_mapping[:name], content_item_field_mappings(field)
      end

      mappings
    end

    def content_item_field_mappings(field)
      mappings = { type: field.elasticsearch_mapping[:type] }
      mappings[:analyzer] = field.elasticsearch_mapping[:analyzer] if field.elasticsearch_mapping[:analyzer]
      mappings
    end
  end
end

app/models/concerns/cortex/searchable_content_type.rb
module Cortex
  module SearchableContentType
    extend ActiveSupport::Concern

    included do
      include Cortex::Searchable

      # TODO: ContentType mappings
    end
  end
end

app/models/cortex/application_record.rb
module Cortex
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true

    acts_as_paranoid

    # A bug in ES-Rails 5.x is breaking document updates:
    # https://github.com/elastic/elasticsearch-rails/issues/669
    after_commit :refresh_elasticsearch_index, on: :update

    private

    def refresh_elasticsearch_index
      __elasticsearch__.index_document(refresh: true) if defined? __elasticsearch__
    end
  end
end

app/models/cortex/content_item.rb
module Cortex
  class ContentItem < Cortex::ApplicationRecord
    include ActiveModel::Transitions

    include Cortex::SearchableContentItem
    include Cortex::BelongsToTenant

    scope :last_updated_at, -> { order(updated_at: :desc).select('updated_at').first.updated_at }

    belongs_to :creator, class_name: 'User'
    belongs_to :updated_by, class_name: 'User', optional: true
    belongs_to :content_type
    has_many :field_items, dependent: :destroy, autosave: true

    accepts_nested_attributes_for :field_items

    default_scope { order(created_at: :desc) }

    validates :creator, :content_type, presence: true

    state_machine do
      state :draft
      state :scheduled

      event :schedule do
        transitions :to => :scheduled, :from => [:draft]
      end

      event :draft do
        transitions :to => :draft, :from => [:scheduled]
      end
    end

    def publish_state
      GetPublishStateTransaction.new.call(self).value!
    end

    # FieldItem and State Convenience Methods. TODO: move to concern? transactions?
    def method_missing(method_name, *arguments, &block)
      super unless dynamic_method?(method_name)

      if dynamic_state_check?(method_name)
        # Used to check state - allows for methods such as #published? and #expired?
        # Will return true if the active_state corresponds to the name of the method
        "#{publish_state.downcase}?" == method_name.to_s
      else
        # Used to query for any field on the relevant ContentType and return data from the content_item
        field_items.find { |field_item| field_item.field.name.parameterize(separator: '_') == method_name.to_s }.data.values.first
      end
    end

    def respond_to_missing?(method_name, include_private = false)
      dynamic_method?(method_name) || super
    end

    private

    def dynamic_method?(method_name)
      dynamic_state_check?(method_name) || has_field_item?(method_name)
    end

    def dynamic_state_check?(method_name)
      method_name.to_s.include? '?'
    end

    # TODO: this logic effectively gets called multiple times (slow?) - how do we optimize or cache the result?
    def has_field_item?(method_name)
      field_items.any? { |field_item| field_item.field.name.parameterize(separator: '_') == method_name.to_s }
    end
  end
end

app/models/cortex/content_type.rb
module Cortex
  class ContentType < Cortex::ApplicationRecord
    include Cortex::SearchableContentType
    include Cortex::SearchableContentItemForContentType
    include Cortex::BelongsToTenant

    validates :name, :creator, :contract, presence: true
    validates_uniqueness_of :name,
                            :name_id,
                            scope: :tenant_id,
                            message: 'should be unique within a Tenant'

    belongs_to :creator, class_name: 'User'
    belongs_to :contract
    has_many :fields
    has_many :content_items
    has_many :contentable_decorators, as: :contentable
    has_many :decorators, through: :contentable_decorators

    accepts_nested_attributes_for :fields

    # TODO: Extract to a concern
    def self.permissions
      Permission.select { |perm| perm.resource_type = self }
    end
  end
end

app/models/cortex/contentable_decorator.rb
module Cortex
  class ContentableDecorator < Cortex::ApplicationRecord
    include Cortex::BelongsToTenant

    belongs_to :decorator
    belongs_to :contentable, polymorphic: true
  end
end

app/models/cortex/contract.rb
# TODO: Refactor
module Cortex
  class Contract < Cortex::ApplicationRecord
    include Cortex::BelongsToTenant

    validates :name, presence: true

    has_many :content_types
    has_many :contentable_decorators, as: :contentable
    has_many :decorators, through: :contentable_decorators
  end
end

app/models/cortex/decorator.rb
module Cortex
  class Decorator < Cortex::ApplicationRecord
    include Cortex::BelongsToTenant

    has_many :contentable_decorators

    validates :name, :data, presence: true

    def data
      self[:data].deep_symbolize_keys
    end
  end
end

app/models/cortex/field.rb
module Cortex
  class Field < Cortex::ApplicationRecord
    belongs_to :content_type, touch: true
    has_many :field_items
    has_many :content_items, through: :field_items

    validates :name, :content_type, :field_type, presence: true
    validate :acceptable_field_type
    validates_uniqueness_of :name,
                            :name_id,
                            scope: :content_type_id,
                            message: 'should be unique within a ContentType'

    def field_type_instance(options = {})
      field_type.camelize.constantize.new(options)
    end

    def elasticsearch_mapping
      field_type_instance(field_name: name).elasticsearch_mapping
    end

    def tenant
      content_type.tenant
    end

    private

    def acceptable_field_type
      begin
        Cortex::FieldType.get_subtype_constant(field_type)
      rescue NameError
        errors.add(:field_type, 'must be an available field type')
      end
    end
  end
end

app/models/cortex/field_item.rb
module Cortex
  class FieldItem < Cortex::ApplicationRecord
    belongs_to :field
    belongs_to :content_item, touch: true

    validates :field, :content_item, presence: true
    validate :field_item_content_is_valid, if: :field_is_present

    def data=(data_hash)
      # Reset @field_type_instance so that massaged data can be re-generated every time @data is set, not just on init
      @field_type_instance = nil
      super(field_type_instance(data_hash).data || data_hash)
    end

    def tenant
      content_item.tenant
    end

    private

    def field_type_instance_params(data_hash)
      # Carefully construct a params object so we don't trigger our fragile setters when a value is nil
      params = { metadata: field.metadata.merge({ existing_data: data }), field: field, validations: field.validations }
      params[:data] = data_hash if data_hash
      params
    end

    def field_type_instance(data_hash = nil)
      field_type_class = FieldType.get_subtype_constant(field.field_type)
      # data_before_typecast will give us a non-mutilated hash with Objects intact, just in case validations get called first
      @field_type_instance ||= field_type_class.new(field_type_instance_params(data_hash))
      @field_type_instance.save
      @field_type_instance
    end

    def field_is_present
      field.present?
    end

    def field_item_content_is_valid
      add_specific_errors unless field_item_validates
    end

    def field_item_validates
      field_type_instance.valid?
    end

    def add_specific_errors
      field_type_instance.errors.each do |k, v|
        errors.add(field.name.to_sym, v)
      end
    end
  end
end

app/models/cortex/field_type.rb
module Cortex
  class FieldType < Cortex::ApplicationRecord
    extend ActiveSupport::DescendantsTracker

    attr_accessor :field_name, :field
    attr_reader :data, :validations, :metadata

    def self.direct_descendant_names
      direct_descendants.map { |descendant| descendant.name.underscore }
    end

    def self.get_subtype_constant(descendant_name)
      descendant_name.camelize.constantize
    end

    def elasticsearch_mapping
      raise 'Not implemented'
    end

    def validations=(validations_hash)
      @validations = validations_hash.deep_symbolize_keys if validations_hash
    end

    def metadata=(metadata_hash)
      @metadata = metadata_hash.deep_symbolize_keys if metadata_hash
    end

    def acceptable_validations?
      valid_types? && valid_options?
    end

    def valid_types?
      validations.all? do |type, options|
        VALIDATION_TYPES.include?(type.to_sym)
      end
    end

    def valid_options?
      validations.all? do |type, options|
        self.send(VALIDATION_TYPES[type])
      end
    end
  end
end

app/models/cortex/permission.rb
module Cortex
  class Permission < Cortex::ApplicationRecord
    has_and_belongs_to_many :roles

    validates :name, :resource_type, presence: true

    def resource
      resource_type.constantize
    end
  end
end

app/models/cortex/role.rb
module Cortex
  class Role < Cortex::ApplicationRecord
    scopify

    has_and_belongs_to_many :users
    has_and_belongs_to_many :permissions

    validates :resource_type,
              :inclusion => { :in => Rolify.resource_types },
              :allow_nil => true
  end
end

app/models/cortex/tenant.rb
module Cortex
  class Tenant < Cortex::ApplicationRecord
    acts_as_nested_set

    has_many :content_items
    has_many :content_types
    has_many :contracts
    has_many :decorators
    has_and_belongs_to_many :users
    belongs_to :owner, class_name: 'User'
    has_many :users, foreign_key: :active_tenant_id, class_name: 'User'

    validates_presence_of :name
    validates_associated :owner

    validates_uniqueness_of :name,
                            :name_id

    alias_method :organization, :root

    def is_organization?
      root?
    end

    def has_children?
      !leaf?
    end

    def all_up_organization_for(klass)
      self_and_ancestors.flat_map do |tenant|
        tenant.public_send(klass.name.demodulize.underscore.pluralize).all
      end
    end

    def search_up_organization_for(klass, attribute, value)
      all_up_organization_for(klass).select do |record|
        record[attribute] == value
      end
    end
  end
end

app/models/cortex/user.rb
require 'digest/md5'

module Cortex
  class User < Cortex::ApplicationRecord
    include HasGravatar
    include HasFirstnameLastname

    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :rememberable, :trackable, :validatable, :recoverable
    rolify role_join_table_name: :roles_users # rolify doesn't obey lexical order for join table names

    has_and_belongs_to_many :tenants
    belongs_to :active_tenant, class_name: 'Tenant', optional: true
    has_many :content_items

    validates_presence_of :email, :firstname, :lastname

    before_destroy :prevent_consumed_deletion

    def active_tenant
      super || tenants.order(:name).first
    end

    def referenced?
      [ContentItem].find do |resource|
        true if resource.where(user: self).count > 0
      end
    end

    def anonymous?
      self.id == nil
    end

    def has_permission?(resource, permission)
      return true if self.is_superadmin?

      resource_class = resource.class
      allowed_perms = allowed_permissions(resource_class, permission)

      if resource_class == Cortex::ContentType
        allowed_perms.select { |perm| perm.resource_id == resource.id }.any?
      else
        allowed_perms.any?
      end
    end

    def gravatar
      "//www.gravatar.com/avatar/#{Digest::MD5.hexdigest email}"
    end

    def tenants_with_children
      tenants.flat_map(&:self_and_descendants)
    end

    private

    def allowed_permissions(resource_class, permission)
      permissions.select { |perm| perm.resource_type == resource_class.to_s && perm.name == permission }
    end

    def prevent_consumed_deletion
      raise Cortex::Exceptions::ResourceConsumed if referenced?
    end

    class << self
      def authenticate(username, password)
        user = User.find_by_email(username)
        user && user.valid_password?(password) ? user : nil
      end

      def anonymous
        User.new
      end
    end
  end
end

app/views/cortex/partials/_breadcrumb.html.haml
%span.mdl-layout-title
  = render_breadcrumbs

app/views/cortex/partials/_cortex_redux_state.html.haml
= redux_store('CortexStore', props: cortex_props )

app/views/cortex/partials/_flash.html.haml
- flash.each do |key, value|
  - unless value == 'You need to sign in or sign up before continuing.'
    - if flash['warning']
      .mdl-snackbar.snackbar__error.mdl-snackbar--active.flash--warning{ 'aria-atomic' => 'true', 'aria-live' => 'assertive', 'aria-relevant' => 'text' }
        %i.mdl-snackbar__close.material-icons close
        .mdl-snackbar__text
          %p.flash--header__text
            Oops! Please review the following fields for errors:
          %ul
          - value.each do |err|
            %li
              %i.material-icons error_outline
              = err
        %button.mdl-snackbar__action{ type: 'button' }
    - elsif flash['success']
      .mdl-snackbar.mdl-js-snackbar.snackbar__message.mdl-snackbar--active.flash--success{ 'aria-atomic' => 'true', 'aria-live' => 'assertive', 'aria-relevant' => 'text' }
        .mdl-snackbar__text
          %i.material-icons check
          = value
        %button.mdl-snackbar__action{ type: 'button' }
    - else
      .mdl-snackbar.mdl-js-snackbar.mdl-snackbar--active{ 'aria-atomic' => 'true', 'aria-live' => 'assertive', 'aria-relevant' => 'text' }
        .mdl-snackbar__text
          = value
        %button.mdl-snackbar__action{ type: 'button' }

app/views/cortex/partials/_media_dialogs.html.haml
- if @content_item
  %dialog.mdl-dialog#wysiwyg
    %h4.mdl-dialog__title Insert Media
    .mdl-dialog__content
      = cell(Cortex::IndexCell, media_index, context: { content_type: content_type, content_items: media_content_items, popup: 'wysiwyg' }).(:index)
    .mdl-dialog__actions
      .mdl-button.mdl-js-button.mdl-button--raised.close-dialog Close
  %dialog.mdl-dialog#featured
    %h4.mdl-dialog__title Select Media
    .mdl-dialog__content
      = cell(Cortex::IndexCell, media_index, context: { content_type: content_type, content_items: media_image_content_items, popup: 'featured' }).(:index)
    .mdl-dialog__actions
      .mdl-button.mdl-js-button.mdl-button--raised.close-dialog Close

app/views/cortex/partials/_navigation.html.haml
%nav.demo-navigation.mdl-navigation
  = link_to dashboards_path, class: "mdl-navigation__link #{'active' if current_page?(dashboards_path) }" do
    %i.material-icons{role: 'presentation'}> dashboard
    %span.nav__item-name
      Dashboard
  = cell(Cortex::ContentTypeCell, collection: current_user.active_tenant.all_up_organization_for(Cortex::ContentType)).(:nav)
  .mdl-layout-spacer
  = link_to graphql_ide_path, class: 'mdl-navigation__link' do
    %i.material-icons{role: 'presentation'} code
    %span.nav__item-name
      GraphQL IDE
  = link_to 'https://docs.cortexcms.org/', class: 'mdl-navigation__link', target: '_blank' do
    %i.material-icons{role: 'presentation'} help_outline
    %span.nav__item-name
      Documentation

app/views/cortex/partials/_notes.html.haml
%table.notes.mdl-data-table.mdl-js-data-table
  %thead
    %tr
      %th.mdl-data-table__cell--non-numeric
        %i.material-icons.f-left.m-r-5 content_paste
        %span.notes__header Notes
      %th
  %tbody
    - news_feed.each do |post|
      %tr
        %td.mdl-data-table__cell--non-numeric
          = post.body.html_safe
        %td
          - post.tags.each do |tag|
            %span.mdl-chip
              %span.mdl-chip__text
                = tag

app/views/cortex/partials/_quick_links.html.haml
%section.quick-links.mdl-grid
  - if employer_blog_content_type
    .mdl-cell.mdl-cell--6-col
      = link_to new_content_type_content_item_path(employer_blog_content_type) do
        .jumbo-button
          %span.jumbo-button__content
            %p.jumbo-button__content__icon
              = image_tag 'cortex/icons/blog.png'
            %p.jumbo-button__content__add
              = image_tag 'cortex/icons/add.svg'
            %p Create a New Post

  - if media_content_type
    .mdl-cell.mdl-cell--6-col
      = link_to new_content_type_content_item_path(media_content_type) do
        .jumbo-button
          %span.jumbo-button__content
            %p.jumbo-button__content__icon
              = image_tag 'cortex/icons/media.png'
            %p.jumbo-button__content__add
              = image_tag 'cortex/icons/add.svg'
            %p Upload Media

app/views/cortex/partials/_sidebar.html.haml
.layout__sidebar.mdl-layout__drawer
  %header.sidebar__header
    = link_to cortex.root_path, class: 'sidebar__root-link' do
      = image_tag 'cortex/logo.svg', class: 'sidebar__brand-logo'
      %h1.sidebar__brand-name Cortex
  = render 'cortex/partials/navigation'
  = react_component('CortexApp', props: { temporary_render: 'TenantSwitcher' })

app/views/cortex/partials/_topbar.html.haml
%header.mdl-layout__header
  .mdl-layout__header-row
    = render 'cortex/partials/breadcrumb'
    .mdl-layout-spacer
    = render 'cortex/partials/user_control'

app/views/cortex/partials/_user_control.html.haml
%div.user-block
  %div.user-block__text
    %span.user-block__greeting
      Hello, #{current_user.firstname}
    %span.user-block__logout
      = link_to 'Logout', destroy_user_session_path, method: :delete
  %img.user-block__avatar{:src => current_user.gravatar}